# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@3122f2c659b52a78671a7862f5bc93f72823bb43
        with:
          arguments: build --refresh-dependencies
      - name: Get Latest Commit ID and save in GITHUB_ENV
        run: echo "COMMIT_ID=$(git rev-parse HEAD | head -c 10)" >> "$GITHUB_ENV"
      - name: "Update README with latest commit id - " $(git rev-parse HEAD | head -c 10)"
        run: |
          echo "COMMIT_ID=$COMMIT_ID"
          awk -v id="$COMMIT_ID" '{gsub("commit-.*-blue", "commit-"id"-blue")}1' README.md > README_new.md
          mv README_new.md README.md
      - name: Commit changes to updated README.md
        run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add README.md
            git commit -m "Update README with latest commit ID - $COMMIT_ID"
            git push --set-upstream origin main
        env:
          COMMIT_ID: ${{ steps.commit_id.outputs.commit }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
